/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.sv.udb.forms;

import com.sv.udb.clases.Iniciales;
import com.sv.udb.clases.Leertxt;
import com.sv.udb.clases.NumeRand;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import java.util.Scanner;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author DanielWilfredo
 */
public class FrmMenuInicial extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenuInicial
     */
      Iniciales ini = new Iniciales();
    public FrmMenuInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEjerci1 = new javax.swing.JButton();
        btnEjerci2 = new javax.swing.JButton();
        btnEjerci3 = new javax.swing.JButton();
        btnEjerci4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Guia 1 :: Wilfredo Granados");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ejercicios Guia 1"));

        btnEjerci1.setBackground(new java.awt.Color(0, 153, 153));
        btnEjerci1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEjerci1.setText("Ejercicio 1");
        btnEjerci1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerci1ActionPerformed(evt);
            }
        });

        btnEjerci2.setBackground(new java.awt.Color(0, 153, 153));
        btnEjerci2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEjerci2.setText("Ejercicio 2");
        btnEjerci2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerci2ActionPerformed(evt);
            }
        });

        btnEjerci3.setBackground(new java.awt.Color(0, 153, 153));
        btnEjerci3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEjerci3.setText("Ejercicio 3");
        btnEjerci3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerci3ActionPerformed(evt);
            }
        });

        btnEjerci4.setBackground(new java.awt.Color(0, 153, 153));
        btnEjerci4.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnEjerci4.setText("Ejercicio 4");
        btnEjerci4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEjerci4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEjerci3, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                    .addComponent(btnEjerci1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEjerci2, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                    .addComponent(btnEjerci4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjerci1, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(btnEjerci2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEjerci3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEjerci4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEjerci2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerci2ActionPerformed
          Leertxt leerArch = new Leertxt();
       String nomb1 = leerArch.ObteText("C:\\Users\\DanielWilfredo\\Documents\\NetBeansProjects\\Guia1-POO1-Wilfredo-Granados-161659\\nombre.txt");
       String apel = leerArch.ObteText("C:\\Users\\DanielWilfredo\\Documents\\NetBeansProjects\\Guia1-POO1-Wilfredo-Granados-161659\\apellido1.txt");
       String apel2 = leerArch.ObteText("C:\\Users\\DanielWilfredo\\Documents\\NetBeansProjects\\Guia1-POO1-Wilfredo-Granados-161659\\apellido2.txt");
      
      System.out.println("Su nombre Completo es: " + nomb1 + " " + apel + " " + apel2 + " " );
      System.out.println("Sus Iniciales son: \n "+ "Nombre: " + nomb1.charAt(0) + "\n Primer Apellido: "
      +  apel.charAt(0) + "\n Segundo Apellido: " + apel2.charAt(0));

    }//GEN-LAST:event_btnEjerci2ActionPerformed

    private void btnEjerci3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerci3ActionPerformed
              List<Integer> guarNume = new ArrayList<Integer>();
        try
        {
           int num, cont=0, cont2=0;
           //num=Integer.parseInt(txtnumero.getText());
        while(cont2 == 0)
        {
         num = Integer.parseInt(JOptionPane.showInputDialog(null, "Ingrese un numero"));
        guarNume.add(num); 
         cont2=0;
         cont=0;
        for(int i:guarNume)
        {
            if (num==i)
            {
                cont++;
               
            }
            if (cont ==3)
                    {
                     JOptionPane.showMessageDialog(null, "El numero " + i + " Ya se repitio 3 veces"); 
                      cont2=1;
                     }
               }
          
        }
                }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this,"Hubo un error " + e.getMessage());
        }
    }//GEN-LAST:event_btnEjerci3ActionPerformed

    private void btnEjerci4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerci4ActionPerformed
        try {
            NumeRand prueba = new NumeRand();
        int cont = Integer.parseInt(JOptionPane.showInputDialog("Ingrese 0 para Generar Cara & 1 si desea finalizar: "));
        while (cont !=1)
        {
             int pru =    prueba.calcNume();
            System.out.println("Cara del dado: " + pru);
          cont = Integer.parseInt(JOptionPane.showInputDialog("Ingrese 0 para Generar Cara & 1 si desea finalizar: "));
        }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"Hubo un error. " + e.getMessage());
        }
        
       
       
     
    }//GEN-LAST:event_btnEjerci4ActionPerformed
    private void btnEjerci1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEjerci1ActionPerformed
       String nomb, apel, apel2; 
        String iniN, iniA1, iniA2;
        Scanner info = new Scanner (System.in);
        System.out.println ("Ingrese su primer nombre: "); 
        nomb = info.nextLine();
        System.out.println("Ingrese su primer apellido: ");
        apel = info.nextLine();
         System.out.println("Ingrese su primer apellido: ");
         apel2 = info.nextLine();
         iniN=  ini.ObtNomb(nomb);
         iniA1= ini.ObtNomb(apel);
         iniA2= ini.ObtNomb(apel2);
         System.out.println("Su nombre Completo es: " + ini.NombComp(nomb, apel, apel2));
         System.out.println("Sus Iniciales son: \n "+ "Nombre: " + iniN + "\n Primer Apellido: "
         + iniA1 + "\n Segundo Apellido: " + iniA2);
    }//GEN-LAST:event_btnEjerci1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEjerci1;
    private javax.swing.JButton btnEjerci2;
    private javax.swing.JButton btnEjerci3;
    private javax.swing.JButton btnEjerci4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
